language: c

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

os: linux

dist: bionic

compiler:
  - gcc
  - clang

jobs:
  exclude:
   - os: linux
     arch: ppc64le
     compiler: clang
   - os: linux
     arch: s390x
     compiler: clang
   - os: linux
     arch: arm64
     compiler: clang

install: skip

script:
  - make prove PROVE_OPTS=-v
  - clang-tidy --version && make -j2 tidy

cache:
  ccache: true
