language: c

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

os: linux

dist: bionic

compiler:
  - gcc
  - clang

jobs:
  exclude:
   - os: linux
     arch: ppc64le
     compiler: clang
   - os: linux
     arch: s390x
     compiler: clang
   - os: linux
     arch: arm64
     compiler: clang

addons:
  apt:
    update: true
    packages:
    - lcov

install: skip

script:
  - if [[ "$TRAVIS_CPU_ARCH" == "amd64" ]]; then
        export COVERAGE=1;
    fi
  - make prove PROVE_OPTS=-v
  - if [[ "$TRAVIS_CPU_ARCH" == "amd64" ]]; then
        clang-tidy --version && make -j2 tidy;
    fi

after_success:
  - if [[ "$TRAVIS_CPU_ARCH" == "amd64" ]]; then
        lcov --directory . --capture --output-file coverage.info
        && bash <(curl -s https://codecov.io/bash);
    fi

cache:
  ccache: true
